module.exports = {
  VERIFY_TOKEN: process.env.VERIFY_TOKEN || 'rifas_verify_123',
  SHEET_ID: process.env.GOOGLE_SHEET_ID,
  CASES_TAB: process.env.GOOGLE_SHEET_TAB || 'cases',
  CONV_TAB: process.env.GOOGLE_SHEET_CONV_TAB || 'conversations',
  SESSIONS_TAB: process.env.GOOGLE_SHEET_SESS_TAB || 'sessions',
  GOOGLE_CLIENT_EMAIL: process.env.GOOGLE_CLIENT_EMAIL,
  GOOGLE_PRIVATE_KEY: (process.env.GOOGLE_PRIVATE_KEY || '').replace(/\\n/g, '\n'),
  WHATSAPP_TOKEN: process.env.WHATSAPP_TOKEN || '',
  PHONE_NUMBER_ID: process.env.PHONE_NUMBER_ID || '',
  META_APP_SECRET: process.env.META_APP_SECRET,
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN || '',
  TELEGRAM_SECRET_TOKEN: process.env.TELEGRAM_SECRET_TOKEN || '',
  TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID || '',
  TELEGRAM_GROUP_ID: process.env.TELEGRAM_GROUP_ID || '',
  GEMINI_API_KEY: process.env.GEMINI_API_KEY || '',
  GEMINI_MODEL_TEXT: process.env.GEMINI_MODEL_TEXT || 'gemini-1.5-flash',
  GEMINI_MODEL_VISION: process.env.GEMINI_MODEL_VISION || 'gemini-1.5-flash',
  MEMORY_TURNS: Number(process.env.MEMORY_TURNS || 10),
};
